services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=sgam_db'
      - 'POSTGRES_USER=sgam_user'
      - 'POSTGRES_PASSWORD=sgam@123'
    ports:
      - '5432:5432'
