services:
  db:
    image: postgres:16
    container_name: sgam_postgres
    environment:
      - POSTGRES_DB=sgam_db
      - POSTGRES_USER=sgam_user
      - POSTGRES_PASSWORD=sgam@123
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sgam_user -d sgam_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: sgam_app
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sgam_db
      - SPRING_DATASOURCE_USERNAME=sgam_user
      - SPRING_DATASOURCE_PASSWORD=sgam@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  pgdata: